# Value of the initial evolution scale in GeV
Initial scale: 0.000510998928

# Perturbative order of the evolution (options: LL, NLL)
Perturbative order: NLL

# Factorisation scheme (options: MSbar, Delta)
Factorisation scheme: MSbar

# Number of leptonic flavour
NL: 1

# Parameters of the running coupling
Alpha:
  evolution: analytic   # analytic, numerical, fixed
  aref: 0.0072973525693
  Qref: 0.000510998928

# Parameters for the numerical solution of the DGLAP equation
PDF:
  evolution: iterative # path ordering, iterative
#  expand: False         # default: True

# Parameters of the Mellin inverse transform
Mellin inverse:
#  contour: straight       # Contour to be used (options: talbot, straight, default: talbot)
  integrator: gauss GSL # Integrator to be used (options: gauss, trapezoid, gauss GSL)
  accuracy: 0.001       # integration accuracy (only for integrator: gauss and gauss GSL)
